services:
  server:
    build:
      context: .
    environment:
      NODE_ENV: production
      REDIS_HOST: redis
      REDIS_PORT: 6379
      MONGO_URI: ${MONGO_URI}
      CLIENT_ID: ${CLIENT_ID}
      CLIENT_SECRET: ${CLIENT_SECRET}
      REDIRECT_URL: ${REDIRECT_URL}
      REDIS_URL: ${REDIS_URL}
    networks:
      - app-network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]  # Enable persistence
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
